spring:
  application:
    name: order-svc

  datasource:
    url: jdbc:mysql://localhost:3306/order-svc
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true                # Bật Flyway
    baseline-on-migrate: true    # Tạo baseline nếu database chưa có lịch sử migration
    locations: classpath:db/migration  # Đường dẫn mặc định chứa các file migration

